apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-cfgmap-secret
  namespace: vk
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sleep-ba
  template:
    metadata:
      labels:
        app: sleep-ba
    spec:
      containers:
      - image: docker://ghcr.io/grycap/cowsay 
        command: ["/bin/sh"]
        # Modify the args to use a variable from the Secret
        args: ["-c",  "\"echo hello > /tmp/test.txt && sleep 10 && cat /config1/message /config2/message | /usr/games/cowsay\"" ]
        #args: ["-c",  "\"touch /tmp/test.txt && sleep 60 && /usr/games/cowsay \"$(cat /config/message.txt)\"\" " ]  
        imagePullPolicy: Always
        name: cowsayo
        # Add the volumeMounts section
        volumeMounts:
        - name: config-volume1  # Mount point name
          mountPath: /config1  # Path inside the container where the config is mounted  
        - name: config-volume2  # Mount point name
          mountPath: /config2  # Path inside the container where the config is mounted  
      # Add the volumes section  
      volumes:
      - name: config-volume1  # Volume name (same as mount point name)
        secret:
          secretName: my-secret2  # Reference the Secret name 
      - name: config-volume2  # Volume name (same as mount point name)
        configMap:
          name: my-configmap2  # Reference the ConfigMap name 
      nodeSelector:
        kubernetes.io/hostname: test-vk
      tolerations:
      - key: virtual-node.interlink/no-schedule
        operator: Exists
      - key: virtual-kubelet.io/provider
        operator: Exists

---

apiVersion: v1
kind: Secret
metadata:
  name: my-secret2
  namespace: vk
data:
  message: "aGVsbG8g"  # This message will be used by the container
type: kubernetes.io/opaque  # Optional, specifies the type of Secret

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap2
  namespace: vk

data:
  message: "muu"  # This message will be used by the container
