apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Name}}-rathole-config
  namespace: {{.Namespace}}
data:
  server.toml: |
    [server]
    bind_addr = "0.0.0.0:2333"
    {{- range .ExposedPorts}}

    [server.services.p{{.Port}}]
    token = "{{$.RandomPassword}}"
    bind_addr = "0.0.0.0:{{.Port}}"
    {{- end}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: {{.Name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{.Name}}
    spec:
      containers:
      - name: rathole
        image: rapiz1/rathole:v0.5.0
        imagePullPolicy: IfNotPresent
        args: ["--server", "/etc/rathole/server.toml"]
        ports:
        - containerPort: 2333
          name: control
          protocol: TCP
        {{- range .ExposedPorts}}
        - containerPort: {{.Port}}
          name: {{if .Name}}{{.Name}}{{else}}port-{{.Port}}{{end}}
          protocol: {{.Protocol}}
        {{- end}}
        volumeMounts:
        - name: rathole-config
          mountPath: /etc/rathole
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
        readinessProbe:
          tcpSocket:
            port: 2333
          initialDelaySeconds: 2
          periodSeconds: 2
          failureThreshold: 10
        livenessProbe:
          tcpSocket:
            port: 2333
          initialDelaySeconds: 10
          periodSeconds: 10
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - name: rathole-config
        configMap:
          name: {{.Name}}-rathole-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: {{.Name}}
  ports:
    - port: 2333
      targetPort: 2333
      name: control
      protocol: TCP
    {{- range .ExposedPorts}}
    {{- if ne .Port 2333}}{{/* skip control port 2333 to avoid conflicts with the rathole server listener */}}
    - port: {{.Port}}
      targetPort: {{.Port}}
      name: {{if .Name}}{{.Name}}{{else}}port-{{.Port}}{{end}}
      {{- if .Protocol}}
      protocol: {{.Protocol}}
      {{- end}}
    {{- end}}
    {{- end}}
