resources:
- virtual-kubelet-config.yaml
- virtual-kubelet.yaml
#- interlink-config.yaml
#- interlink.yaml
#- plugin-k8s-config.yaml
#- plugin.yaml
patches:
- path: virtual-kubelet-merge.yaml
  target:
    kind: Deployment
    labelSelector: nodeName=virtual-kubelet

