apiVersion: v1
kind: Service
metadata:
  name: plugin 
  namespace: interlink
spec:
  selector:
    app: plugin 
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plugin 
  namespace: interlink
  labels:
    app: plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plugin 
  template:
    metadata:
      labels:
        app: plugin
    spec:
      containers:
      - name: plugin 
        image: "dciangot/docker-plugin:v1"
        #image: "ghcr.io/intertwin-eu/interlink-sidecar-slurm/interlink-sidecar-slurm:0.2.3"
        imagePullPolicy: Always
        command:
          - bash
          - -c
        args:
          - dockerd --mtu 1450 & /sidecar/docker-sidecar
        securityContext:
          privileged: true
        env:
        - name: INTERLINKCONFIGPATH
          value: "/etc/interlink/InterLinkConfig.yaml"
        volumeMounts:
        - name: config
          mountPath: /etc/interlink/InterLinkConfig.yaml
          subPath: InterLinkConfig.yaml
      volumes:
      - name: config
        configMap:
          # Provide the name of the ConfigMap you want to mount.
          name: plugin-config
