FROM golang:1.22 as build-stage

WORKDIR /app

COPY .. .

ENV GOMODCACHE="/go/pkg/mod"

ENV GOCACHE="/go/build-cache"

RUN mkdir -p $GOMODCACHE && mkdir -p $GOCACHE


RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o bin/interlink cmd/interlink/main.go

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11:latest AS build-release-stage

WORKDIR /

COPY --from=build-stage /app/bin/interlink /interlink

USER nonroot:nonroot

ENTRYPOINT ["/interlink"]
