apiVersion: v1
data:
  InterLinkConfig.yaml: |
    InterlinkURL: https://{{.InterLinkIP}}
    InterlinkPort: {{.InterLinkPort}}
    CommandPrefix: ""
    ExportPodData: true
    ServiceAccount: "interlink"
    Namespace: {{.Namespace}}
    VKTokenFile: /opt/interlink/token
kind: ConfigMap
metadata:
  name: "{{.VKName}}-config"
  namespace: {{.Namespace}} 
---
apiVersion: v1
data:
  interlink-cfg.json: |
    {
      "{{.VKName}}": {
        "cpu": "{{.VKLimits.CPU}}",
        "memory": "{{.VKLimits.Memory}}",
        "pods": "{{.VKLimits.Pods}}"
      }
    }
kind: ConfigMap
metadata:
  name: "{{.VKName}}-config-json"
  namespace: {{.Namespace}} 
