#!/bin/bash
# start-vk.sh - Start Virtual Kubelet for local testing
# This script is generated by local-test.sh to make VK startup easier

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

echo "=== Starting Virtual Kubelet ==="
echo ""

# Cross-platform IP detection
if command -v hostname &>/dev/null && hostname -I &>/dev/null 2>&1; then
  export POD_IP=$(hostname -I | awk '{print $1}')
else
  export POD_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | head -1 | awk '{print $2}')
fi

export NODENAME=virtual-kubelet-2
export KUBELET_PORT=10250
export KUBELET_URL=0.0.0.0
export CONFIGPATH="${PROJECT_ROOT}/scripts/virtual-kubelet-config.yaml"

# Create token-based kubeconfig
echo "Creating token-based kubeconfig..."
VK_TOKEN=$(kubectl create token virtual-kubelet -n default --duration=24h)
K8S_SERVER=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}')

# Check if certificate-authority-data exists, otherwise use certificate-authority file
K8S_CA_DATA=$(kubectl config view --minify --raw -o jsonpath='{.clusters[0].cluster.certificate-authority-data}')
K8S_CA_FILE=$(kubectl config view --minify --raw -o jsonpath='{.clusters[0].cluster.certificate-authority}')

if [ -n "$K8S_CA_DATA" ]; then
  cat >/tmp/vk-kubeconfig.yaml <<EOF
apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    server: ${K8S_SERVER}
    certificate-authority-data: ${K8S_CA_DATA}
contexts:
- name: default-context
  context:
    cluster: default-cluster
    user: virtual-kubelet
    namespace: default
current-context: default-context
users:
- name: virtual-kubelet
  user:
    token: ${VK_TOKEN}
EOF
elif [ -n "$K8S_CA_FILE" ] && [ -f "$K8S_CA_FILE" ]; then
  # Use certificate-authority file and encode it (cross-platform base64)
  if base64 --help 2>&1 | grep -q -- '-w'; then
    K8S_CA_DATA=$(cat "$K8S_CA_FILE" | base64 -w 0)
  else
    K8S_CA_DATA=$(cat "$K8S_CA_FILE" | base64)
  fi
  cat >/tmp/vk-kubeconfig.yaml <<EOF
apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    server: ${K8S_SERVER}
    certificate-authority-data: ${K8S_CA_DATA}
contexts:
- name: default-context
  context:
    cluster: default-cluster
    user: virtual-kubelet
    namespace: default
current-context: default-context
users:
- name: virtual-kubelet
  user:
    token: ${VK_TOKEN}
EOF
else
  echo "ERROR: Could not find CA certificate"
  exit 1
fi

export KUBECONFIG=/tmp/vk-kubeconfig.yaml

echo "Virtual Kubelet environment:"
echo "  NODENAME: ${NODENAME}"
echo "  KUBELET_PORT: ${KUBELET_PORT}"
echo "  KUBELET_URL: ${KUBELET_URL}"
echo "  POD_IP: ${POD_IP}"
echo "  CONFIGPATH: ${CONFIGPATH}"
echo "  KUBECONFIG: ${KUBECONFIG} (token-based)"
echo ""

cd "${PROJECT_ROOT}"

echo "Starting Virtual Kubelet..."
echo "Logs will be displayed below. Press Ctrl+C to stop."
echo ""

go run ./cmd/virtual-kubelet/main.go
