---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-vk
  labels:
    nodeName: test-vk
spec:
  replicas: 1
  selector:
    matchLabels:
      nodeName: test-vk
  template:
    metadata:
      labels:
        nodeName: test-vk
    spec:
      initContainers:
      - name: settoken
        image: "docker.io/alpine:3"
        command: ["sh", "-c"]
        args: ["touch /opt/interlink/token"]
        volumeMounts:
        - name: token
          mountPath: /opt/interlink
      containers:
      # podman otlp
      # podman run -d --name jaeger   -e COLLECTOR_OTLP_ENABLED=true   -e COLLECTOR_ZIPKIN_HOST_PORT=:9411   -p 5775:5775/udp   -p 6831:6831/udp   -p 6832:6832/udp   -p 5778:5778   -p 16686:16686   -p 14250:14250   -p 14268:14268   -p 14269:14269   -p 4317:4317   -p 4318:4318   -p 9411:9411   jaegertracing/all-in-one:1.47
      - name: inttw-vk
        image: ghcr.io/intertwin-eu/virtual-kubelet-inttw:latest 
        imagePullPolicy: Always
        #command: ["sleep", "infinity"]
        env:
        - name: NODENAME
          value: test-vk
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        #- name: KUBECONFIG
        #  value: /etc/interlink/kubeconfig
        - name: KUBELET_PORT
          value: "10255"
        - name: INTERLINKCONFIGPATH
          value: "/etc/interlink/InterLinkConfig.yaml"
        - name: VKTOKENFILE
          value: "/opt/interlink/token"
        - name: CONFIGPATH
          value: "/etc/interlink/vk-cfg.json"
        volumeMounts:
        - name: config
          mountPath: /etc/interlink/InterLinkConfig.yaml
          subPath: InterLinkConfig.yaml
        - name: config-json
          mountPath: /etc/interlink/vk-cfg.json
          subPath: vk-cfg.json
        - name: token
          mountPath: /opt/interlink
        resources:
          limits:
            cpu: 500m
            memory: 600Mi
          requests:
            cpu: 50m
            memory: 100Mi
      - name: refresh-token
        image: ghcr.io/intertwin-eu/virtual-kubelet-inttw-refresh:latest
        imagePullPolicy: Always
        env:
        - name: IAM_SERVER
          value: "https://dodas-iam.cloud.cnaf.infn.it/"
        # TODO load env IAM client from secret
        - name: IAM_CLIENT_ID
          value: "DUMMY"
        - name: IAM_CLIENT_SECRET
          value: "DUMMY"
        - name: IAM_REFRESH_TOKEN
          value: "DUMMY"
        - name: IAM_VK_AUD
          value: intertw-vk
        - name: TOKEN_PATH
          value: /opt/interlink/token
        resources:
          limits:
            cpu: 500m
            memory: 600Mi
          requests:
            cpu: 50m
            memory: 100Mi
        volumeMounts:
        - name: token
          mountPath: /opt/interlink
      serviceAccountName: interlink
      volumes:
      - name: config
        configMap:
          # Provide the name of the ConfigMap you want to mount.
          name: vk-config
      - name: config-json
        configMap:
          # Provide the name of the ConfigMap you want to mount.
          name: test-vk-config
      - name: token
        emptyDir: {}
