# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: "interlink-config"
#   namespace: interlink 
# data:
#   InterLinkConfig.yaml: |
    #InterlinkAddress: "unix:///var/run/interlink.socket"
interlinkAddress: "http://0.0.0.0"
interlinkPort: "3000"
#sidecarURL: "http://plugin"
sidecarURL: "http://0.0.0.0"
sidecarPort: "4000"
verboseLogging: true
errorsOnlyLogging: false
dataRootFolder: "~/.interlink"
