apiVersion: v1
kind: ServiceAccount
metadata:
  name: virtual-kubelet 
  namespace: interlink
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtual-kubelet 
  namespace: interlink
rules:
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - update
  - create
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  - serviceaccounts
  - namespaces
  verbs:
  - get
  - list
  - watch
# For https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs:
  - create
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtual-kubelet 
  namespace: interlink
subjects:
- kind: ServiceAccount
  name: virtual-kubelet
  namespace: interlink
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: virtual-kubelet

