apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-kubelet
  namespace: interlink
  labels:
    nodeName: virtual-kubelet
spec:
  replicas: 1
  selector:
    matchLabels:
      nodeName: virtual-kubelet
  template:
    metadata:
      labels:
        nodeName: virtual-kubelet 
    spec:
      automountServiceAccountToken: true
      serviceAccountName: virtual-kubelet 
      containers:
      - name: inttw-vk
        image: "ghcr.io/intertwin-eu/virtual-kubelet-inttw:latest" 
        imagePullPolicy: Always
        env:
        - name: NODENAME
          value: virtual-kubelet 
        - name: KUBELET_PORT
          value: "10250"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CONFIGPATH
          value: "/etc/interlink/InterLinkConfig.yaml"
        volumeMounts:
        - name: config
          mountPath: /etc/interlink/InterLinkConfig.yaml
          subPath: InterLinkConfig.yaml
      - name: jaeger
        image: jaegertracing/all-in-one:1.51
      volumes:
      - name: config
        configMap:
          # Provide the name of the ConfigMap you want to mount.
          name: virtual-kubelet-config
