name: build-images

on:
  push:
    tags:
      - "*"
jobs:
  core-containers:
    runs-on: ubuntu-latest
    env:
        GH_REPO_OWNER: ${{ github.repository_owner }} 
    #env:
    #  DOCKER_TARGET_PLATFORM: linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')

      # See https://docs.docker.com/build/ci/github-actions/cache/ for cache to speed go build
      - name: Go Build Cache for Docker
        uses: actions/cache@v4
        with:
          path: go-build-cache
          key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}
      - name: Inject go-build-cache
        uses: reproducible-containers/buildkit-cache-dance@4b2444fec0c0fb9dbf175a96c094720a692ef810 # v2.1.4
        with:
          cache-source: go-build-cache

      - name: Build container base image vk
        uses: docker/build-push-action@v5
        with:
          context: ./
          outputs: "type=registry,push=true"
          tags: |
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/interlink/virtual-kubelet-inttw:${{ env.RELEASE_VERSION }}
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/interlink/virtual-kubelet-inttw:latest
          file: ./docker/Dockerfile.vk
          platforms: linux/amd64, linux/arm64, linux/aarch64
          build-args: |
            VERSION=${{ env.RELEASE_VERSION }} 
      - name: Build container base image interlink
        uses: docker/build-push-action@v5
        with:
          context: ./
          outputs: "type=registry,push=true"
          tags: |
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/interlink/interlink:${{ env.RELEASE_VERSION }}
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/interlink/interlink:latest
          file: ./docker/Dockerfile.interlink
          platforms: linux/amd64, linux/arm64, linux/aarch64
          
  virtual-kubelet-refresh-token:
    runs-on: ubuntu-latest
    #env:
    #  DOCKER_TARGET_PLATFORM: linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - name: Build container base image
        uses: docker/build-push-action@v5
        with:
          context: ./
          outputs: "type=registry,push=true"
          tags: |
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/interlink/virtual-kubelet-inttw-refresh:${{ env.RELEASE_VERSION }}
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/interlink/virtual-kubelet-inttw-refresh:latest
          file: ./docker/Dockerfile.refresh-token
          platforms: linux/amd64, linux/arm64, linux/aarch64
